/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _WRITE_FILE_H_RPCGEN
#define _WRITE_FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char file_data[1024];
	char file_name[1024];
};
typedef struct data data;

#define TRANSFER_PROG 0x23451111
#define TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define transfer 1
extern  int * transfer_1(data *, CLIENT *);
extern  int * transfer_1_svc(data *, struct svc_req *);
extern int transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define transfer 1
extern  int * transfer_1();
extern  int * transfer_1_svc();
extern int transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_WRITE_FILE_H_RPCGEN */
