/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "write_file.h"

int *
transfer_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	FILE *fp;
	fp = fopen(argp->file_name, "ab+");
	if (fp == NULL) {
               printf("Error in writing file");
               result = 1;
        } else {
        	fwrite(argp->file_data, 1, 1024, fp);
       	result = 0;
        }
        
	return &result;
}
